### ISSUE TITLE
This project uses the same style of Spring doc resources?

### ISSUE THREAD

**Issue by hantsy** [spring-io/asciidoctor-spring-backends#1]
I am using https://github.com/spring-io/spring-doc-resources in my personal project to produce HTML, this project use the same styles of  Spring doc resources?

**Comment by philwebb** [comment]
Quite similar, although some of the CSS is based on https://gitlab.com/antora/antora-ui-default. It also provides a lot more more features than we can with the spring-doc-resources project. We're likely to migrate projects away from spring-doc-resources when we iron out all the kinks.
